---
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/tbmatuka/godockercron
          - github.com/spf13/cobra
          - github.com/fsnotify/fsnotify
          - github.com/go-co-op/gocron
          - github.com/docker/docker
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  tagliatelle:
    case:
      rules:
        yaml: snake
  gci:
    local-prefixes: github.com/tbmatuka/godockercron

linters:
  enable-all: true
  disable:
    - golint # deprecated, replaced with revive
    - interfacer # deprecated
    - maligned # deprecated
    - gosmopolitan
    - wrapcheck
    - nlreturn
    - gomnd
    - goerr113
    - exhaustivestruct
    - wsl
    - whitespace
    - lll
    - scopelint
    - nestif
    - funlen
    - paralleltest
    - godot
    - gofumpt
    - goimports
    - varnamelen
    - ireturn
    - ifshort
    - thelper
    - wastedassign
    - goconst
    - gci
    - exhaustruct
    - nonamedreturns
    - interfacebloat
    - dupword
    - forcetypeassert #tmp needs to be on
    - ifshort # deprecated
    - structcheck # deprecated
    - deadcode # deprecated
    - nosnakecase # deprecated
    - varcheck # deprecated
    - rowserrcheck # deprecated
    - sqlclosecheck # deprecated
    - wastedassign # deprecated
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated

run:
  skip-dirs:
    - test
  skip-files:
    - ".*_test\\.go$"
